### ISSUE TITLE
Add compatibility for Windows

### ISSUE THREAD

**Issue by ahill187** [ivadomed/ivadomed#604] opened 2021-01-07 21:00 UTC
We would like to add compatibility for `Windows` in `ivadomed`. Currently we are only `Linux` and `Mac` compatible.

### Motivation for the feature
In this review, some of the reviewers mentioned that they had issues trying to install `ivadomed` on `Windows`: https://github.com/openjournals/joss-reviews/issues/2868#issuecomment-752687437

### Description of the feature
To address the issue in the review, we will add to our documentation that we do not currently support Windows. However, it would be nice to support Windows in the future.

**Comment by dyt811** [comment] 2021-03-14 21:37
So, a quick recap on the potential process to start tackling this as it may become a multi-headed beasts soon if we start unearth more issues. 

Per IvadoMed Meeting agenda discussion item [here](https://docs.google.com/document/d/19mEHKOZKFdprb3UPQYxmfO46mn0bPQfOgE-WPdeF7AQ/edit#heading=h.3ndjkvlk9ktj) at the time, there does not appear to be any underlying libraries that fundamentally prevents the adoption of IvadoMed as library or usable binary on Windows platform. Further extensive and comprehensive validation and testing are required to ensure Windows compatibility and  accompanying concerns. 

So, in light of that, what I propose as simple and rather naïve starting steps to attempt to resolve this: 

1. Examine existing unit tests performance on Windows (as preliminary results already indicating a few unit tests are failing). 
2. Evaluate the cases where they are failing (with GPU or with CPU, as failed test cases appear to VARY). More issues might needs to be unearthed, identified/opened soon based on these.
3. Issue PR fixes and supplement existing unit tests to address above concern. 
4. Documentation update to address limitations or potential issues once complete. 
5. Issue PR to conclude Documentation update. 

More details to be updated.

**Comment by ssinad** [comment] 2021-03-14 21:53
> So, a quick recap on the potential process to start tackling this as it may become a multi-headed beasts soon if we start unearth more issues.
> 
> Per IvadoMed Meeting agenda discussion item [here](https://docs.google.com/document/d/19mEHKOZKFdprb3UPQYxmfO46mn0bPQfOgE-WPdeF7AQ/edit#heading=h.3ndjkvlk9ktj) at the time, there does not appear to be any underlying libraries that fundamentally prevents the adoption of IvadoMed as library or usable binary on Windows platform. Further extensive and comprehensive validation and testing are required to ensure Windows compatibility and accompanying concerns.
> 
> So, in light of that, what I propose as simple and rather naïve starting steps to attempt to resolve this:
> 
>     1. Examine existing unit tests performance on Windows (as preliminary results already indicating a few unit tests are failing).
> 
>     2. Evaluate the cases where they are failing (with GPU or with CPU, as failed test cases appear to VARY). More issues might needs to be unearthed, identified/opened soon based on these.
> 
>     3. Issue PR fixes and supplement existing unit tests to address above concern.
> 
>     4. Documentation update to address limitations or potential issues once complete.
> 
>     5. Issue PR to conclude Documentation update.
> 
> 
> More details to be updated.

I have rewritten some of the tests to work on Windows [here](https://github.com/ssinad/ivadomed/blob/master/.github/workflows/run_tests.yml). I haven't made a pull request yet as the priority was low.
The major issue is that PyTorch Windows wheel is not available on PyPI, so it has to be downloaded from PyTorch's server itself.

**Comment by dyt811** [comment] 2021-03-26 04:36
Further investigation into this issue has confirmed complications that @ssinad has mentioned, 1.5.0 not available on Windows. A supplementary optional conda.yaml has been generated to help automated conda environment setup in single step. Pip sole setup is typically not enough for GPU heavy ML/DL  project because CUDA, CUDNN setup may be required which PIP cannot handle to install. So far, have not found away get those pathed properly except manually. Therefore a conda heavy approach is extremely appreciated here... if possible. 

As for test, CPU based pytest result in the following error: [2021-03-26T002118EST_AutomatedTrainingLog.txt](https://github.com/ivadomed/ivadomed/files/6209377/2021-03-26T002118EST_AutomatedTrainingLog.txt)

Ongoing investigation needed as I dive into automated  "test_automate_training_run_test". 

To be updated.

**Comment by dyt811** [comment] 2021-04-06 06:25
Further investigation into this issue suggestions it is happening around `evaluate()` function, specifically when subj_acq is encoded into the results_pred["image_id"] as [that is the main place image_id is updated](https://github.com/ivadomed/ivadomed/search?q=image_id). Given the platform specific nature when core logic is in tact (i.e. Ubuntu/MacOS functions past without issue). All signs suggest it is highly likely related to pathing and how that is handled in Windows, likely string pathing vs object oriented passing will probably help resolve this problem. Still digging.

**Comment by dyt811** [comment] 2021-04-12 02:26
Further investigation into the issue INDEED suggest this is a PATH related problem. 

![image](https://user-images.githubusercontent.com/6720068/114331441-fad5d880-9b11-11eb-82e7-ddc23d699125.png)

This suggests that all predictions are not being saved to the right place on Windows platform and this bug exists in the "testing.py" module affecting all Windows users of IvadoMed functionalities! 

This further emphasize the importance of having Pathlib adoption to further avoid the way to parse path as shown in the screenshot. 

The reason the unit test failed on Windows side is because the way malformed path is being interpreted across both platform. 

On Windows platform, the prediction files were formed but were not placed in the proper location. 

Amazing... how this worked on the Linux platform. How... did that even work? 

Primary Recommendations: 
- Cease using relative pathing for file references. Internally, always convert path to absolute path ASAP. 
- Avoid string path manual parsing. It is not cross-os compatible and cause weird malformation as shown above.

**Comment by ssinad** [comment] 2021-04-12 02:39
You can use either pathlib.PurePath.name
<https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name> or
os.path.basename()
<https://docs.python.org/3/library/os.path.html#os.path.basename> to
address the second recommendation.

**Comment by dyt811** [comment] 2021-04-12 02:41
Yup. A fix has been implemented and now all the unit tests are passing on windows CPU tests at least.  Gonna test it out more on GPU base and see before getting a PR opened up. 

![image](https://user-images.githubusercontent.com/6720068/114333741-037cdd80-9b17-11eb-99fd-d5a67376418b.png)

**Closed** 2021-04-13 17:50 UTC
Labels: documentation, enhancement, priority:medium, testing
